import type { Metadata } from "next";
import { Viewport } from "next";
import "./globals.css";
import { ysabeauO } from "./font";
import Header from "@src/app/components/header";
import Footer from "@src/app/components/footer";
import ThemeProvider from "@src/app/components/ThemeProvider";
import BodyWrapper from "@src/app/hydrationWrapper";
import Providers from "./providers";
import { auth } from "@src/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 5,
  userScalable: true,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html
      lang="en"
      className={ysabeauO.className}
    >
      <BodyWrapper className="">
        <Providers session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </Providers>
      </BodyWrapper>
    </html>
  );
}
