import type { Metadata } from "next";
import { Viewport } from "next";
import "./globals.css";
import { ysabeauO } from "./font";
import Header from "@src/app/components/header";
import Footer from "@src/app/components/footer";
import ThemesProvider from "@src/app/components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 5,
  userScalable: true,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* suppressHydrationWarning? */}
      <body className={ysabeauO.className}>
        <ThemesProvider>
          <Header />
          {children}
          <Footer />
        </ThemesProvider>
      </body>
    </html>
  );
}
